### ISSUE TITLE
Expose explain plan

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#231]
This is backend specific, but would need to be enabled here first.  It would be nice as a client to get an explain plan back from the backend.  I propose simply have the backend do an explain or whatever if possible and lightblue returns the raw response.  This will help folks see if they are using the expected indexes for a query in the cases when performance might not be as good as expected.

**Comment by bserdar** [comment]
This is partly done in: https://github.com/lightblue-platform/lightblue-core/pull/608

ExecutionPlan.toJson() returns the execution plan. More needs to be done:
 - Search nodes in execution plan should call backend explain() and add to the output
 - Add new query option to return the execution plan instead of query results.
