### ISSUE TITLE
Fix Travis file to make travis deploy the jars

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-core#302]
The after_success script is not running making every PR merged not accessible for those who depends on it. I already made 2 PR to fix it. Need to do on the other repositories.

Example of PR that can solve the issue:
https://github.com/lightblue-platform/lightblue-core/pull/301
https://github.com/lightblue-platform/lightblue-rdbms/pull/101

**Comment by jewzaam** [comment]
Will take review of repos not fixed and push straight to master.  Will leave this open as a reminder.

**Comment by jewzaam** [comment]
They're all updated.  Since this is specific to deployment I pushed things straight to master.

https://github.com/lightblue-platform/lightblue-mongo/commit/1ea80a87f41543ea8cdcb683a11f8e008e84bcfa
https://github.com/lightblue-platform/lightblue-ldap/commit/505ebeeabc91d0a8c481952b9a8e9e01796bf725
https://github.com/lightblue-platform/lightblue-applications/commit/162783a8a0d4b3501b93106588f453e49ce86c10
https://github.com/lightblue-platform/lightblue-client/commit/9bc010748c6e63546b3157af66f1bd6591235831
https://github.com/lightblue-platform/lightblue-migrator/commit/f52d2e639c2c6dd8f1d830d0a751a06d382a745f
https://github.com/lightblue-platform/lightblue-rest/commit/4cc0be35c3326a70545c3454d51a9e81a933493e
https://github.com/lightblue-platform/lightblue-audit-hook/commit/c8cfe16308d73b2fd0386d7accb13f8f39b48cd3

**Comment by jewzaam** [comment]
Closing as everything seems ok now.
