### ISSUE TITLE
Consistency in how lightblue treats null values in arrays

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#592]
This ticket replaces https://github.com/lightblue-platform/lightblue-mongo/issues/215

An update and insert will treat null values differently at least in an array. Uncertain at this time how a save operations handles this. This story is to investigate and make changes so that the three operations treat null array values the same.

**Comment by alechenninger** [comment]
@bserdar @dcrissman We now have code that relies on update keeping nulls, and code that expects inserts/saves to remove nulls. This is pretty frustrating. My ask would be to please keep nulls as is, especially for the use case where array index is significant, so removing nulls is transforming the data in a surprising way.

I find it similar to oracle changing "" to null, which has similar gotchyas. It's a nice sentiment to prevent nulls, but my 2c is this should be done in client code instead of lightblue to keep lightblue flexible and unsurprising.

**Comment by alechenninger** [comment]
@dcrissman To answer your question above, save has same behavior as insert.

**Comment by bserdar** [comment]
What code relies on keeping nulls? Field value being null means field does
not exist.

**Comment by alechenninger** [comment]
Its values in an array.

Update.set with ["foo", null, null, "bar"] makes the array stored as ["foo", null, null, "bar"] (expected)

Insert or save with ["foo", null, null, "bar"] makes the array stored as ["foo", "bar"] (unexpected)

**Comment by bserdar** [comment]
nulls in arrays should be preserved I think.

**Comment by alechenninger** [comment]
Dennis is reporting they are not with inserts, I can see in tests they are not with saves

**Comment by alechenninger** [comment]
@bserdar What do you think of the LOE of fixing this? I may take a look if you don't have time. We talked a bit after planning today and came to consensus it would be good if this could go out before full proxy, but not a must have.

**Comment by bserdar** [comment]
LOE should not be significant, and mainly should go to testing. I think the semantincs would be:
 1) Assigning a field to null removes it from document
 2) Assigning in array element to null preserves that array element

Similarly,
 1) No null field values should be returned
 2) Null array elements should be returned

The implementation is scattered. Mainly:
- JsonDoc.filterNulls
- Projector.project
